CREATE TABLE MEMBROS (
    MEMBRO_ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    TELEFONE VARCHAR2(15),
    EMAIL VARCHAR2(100)
);


CREATE TABLE PLANOS_TREINAMENTO (
    PLANO_ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    DURACAO_SEMANAS NUMBER
);


CREATE TABLE EXERCICIOS (
    EXERCICIO_ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50),
    DESCRICAO CLOB
);


CREATE TABLE HISTORICO_TREINAMENTO (
    HISTORICO_ID NUMBER PRIMARY KEY,
    MEMBRO_ID NUMBER,
    PLANO_ID NUMBER,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    STATUS VARCHAR2(50),
    FOREIGN KEY (MEMBRO_ID) REFERENCES MEMBROS(MEMBRO_ID),
    FOREIGN KEY (PLANO_ID) REFERENCES PLANOS_TREINAMENTO(PLANO_ID)
);


CREATE TABLE ROTINAS_TREINAMENTO (
    ROTINA_ID NUMBER PRIMARY KEY,
    PLANO_ID NUMBER,
    EXERCICIO_ID NUMBER,
    SERIES NUMBER,
    REPETICOES NUMBER,
    DESCANSO_SEGUNDOS NUMBER,
    FOREIGN KEY (PLANO_ID) REFERENCES PLANOS_TREINAMENTO(PLANO_ID),
    FOREIGN KEY (EXERCICIO_ID) REFERENCES EXERCICIOS(EXERCICIO_ID)
);
